name: "PR Reviewer Slack Notify"
description: "Slide into DMs when adding people to review your PR."
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
